analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.8273491598665714
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3727813200093806
  brandStrength: 0.4511698151472956
  rhythmicContrast: 0.2042953053023666
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.4406244345009327
purpose: []
favicon: null
name: tribehire
typography_spectrum: 0.3156076744198799
